### PR TITLE
Use autoconf rather than platform specific defines

### PR DESCRIPTION
**Pull request by lfourquaux**
This is an attempt to remove most of the ifdef __FreeBSD__ and replace them by autoconf tests.

### CODE REVIEW

**Comment by garlick** [comment]
Sorry if I gave the impression that I wanted large commits.  This one goes a beyond doing what its description says and IMHO is too large.  The other changes like the platform-specific enables need to be broken out to their own commit with their own descriptions and explanations please.

I haven't reviewed content yet.  I'll hold off until you give me smaller bites to chew on :-)

**Comment by lfourquaux** [comment]
No problem, here it is in incremental style.

**Comment by lfourquaux** [comment]
Thanks!

Are you sure you prefer to squash together the user.c commits?  I believe this would break tracing the content of user-linux.c and user-stub.c back to the original user.c, and make it look to git like these files were created from scratch.

**Comment by garlick** [comment]
> Are you sure you prefer to squash together the user.c commits? I believe this would break tracing the content of user-linux.c and user-stub.c back to the original user.c, and make it look to git like these files were created from scratch.

You are right!  Sorry, took me a bit to understand what was happening there.  I'll merge as is - thanks!

**Comment by lfourquaux** [comment]
Thanks!

**Pull request merged**
