### PR TITLE
handle some malformed 9P requests gracefully

### PR DESCRIPTION
**Pull request by garlick**
This fixes diod's poor (segfaulting) handling of a couple of malformed requests reported by @rtmrtmrtmrtm.

### CODE REVIEW

**Review by grondo — APPROVED** [review]
LGTM!

**Comment by grondo** [comment]
Hmm, one comment got dropped. typo 'reqst' in df07c796fe620e5f0e2d8ed47678efea0982230

**Comment by garlick** [comment]
Thanks!  Fixed that and rebased. I'll set MWP.

**Comment by garlick** [comment]
@mergifyio requeue

**Comment by garlick** [comment]
@Mergifyio requeue

**Pull request merged**
