### PR TITLE
auto.diod.in: remove bashisms

### PR DESCRIPTION
**Pull request by snogge**
This patch was originally contributed by Roy Li to https://git.yoctoproject.org/meta-virtualization/

### CODE REVIEW

**Review by garlick — APPROVED** [review]
LGTM!

**Comment by garlick** [comment]
If I recall, ubuntu-18.04 is no longer available in github ci so that's probably why those builds are not running.

I merged the other PR.  Would you mind rebasing this on current master?   I'd like to keep a linear history when possible.

Also - thanks for the improvements!

**Comment by snogge** [comment]
Branch rebased.  Thank you for the quick response.

**Comment by snogge** [comment]
Merging this PR will fix #95.

**Pull request merged**
